In [2]:
from gym import Env
from gym.spaces.discrete import Discrete
from gym.spaces import Box, Dict, Discrete, MultiDiscrete
import numpy as np
from models.System_Models import Chiller, Tower, Pump, Fan, Exchanger, AHU
from models.Environment_Models import Air_Node, Water_Node, Room, Outdoor

from stable_baselines3 import PPO 

from stable_baselines3.common.vec_env import dummy_vec_env

from stable_baselines3.common.policies import BasePolicy 

from stable_baselines3.common.env_checker import check_env

from models.RL_Models import GuBeiEnv

import random

In [3]:
env = GuBeiEnv()
check_env(env)

In [4]:
env = GuBeiEnv()

model = PPO(policy = "MlpPolicy", env = env, verbose = 1)

Using cpu device
Wrapping the env with a `Monitor` wrapper
Wrapping the env in a DummyVecEnv.


In [5]:
model.learn(total_timesteps= 10)

---------------------------------
| rollout/           |          |
|    ep_len_mean     | 10       |
|    ep_rew_mean     | -24.1    |
| time/              |          |
|    fps             | 486      |
|    iterations      | 1        |
|    time_elapsed    | 4        |
|    total_timesteps | 2048     |
---------------------------------


In [6]:
obs = env.reset()


In [7]:
actions = []
observations = []
rewards = []
for i in range(100):
    #print(i)
    action, _states = model.predict(obs, deterministic=True)
    obs, reward, done, info = env.step(action)

    #后续要将其它被动参数放入env.state/obs中，可以在env里头设定一个物理引擎，然后在这个外部循环引进被动参数或者环境参数的真实值
    # obs的部分参数 与 what we really got参数数值相互对比，误差可以反馈给env的物理引擎使其可以自我纠正

    actions.append(action)
    observations.append(obs)
    rewards.append(reward)

    env.render()
    if done:
        obs = env.reset()
    
env.close()

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29
30
31
32
33
34
35
36
37
38
39
40
41
42
43
44
45
46
47
48
49
50
51
52
53
54
55
56
57
58
59
60
61
62
63
64
65
66
67
68
69
70
71
72
73
74
75
76
77
78
79
80
81
82
83
84
85
86
87
88
89
90
91
92
93
94
95
96
97
98
99


In [8]:
observations

[array([  29,  988, 3460, 6024]),
 array([  25, 1320, 3524, 6024]),
 array([  28, 1552, 3588, 6024]),
 array([  25, 1426, 3652, 6024]),
 array([  27, 1008, 3588, 6024]),
 array([  28, 1345, 3588, 6024]),
 array([  27, 1381, 3524, 6024]),
 array([  24,  903, 3588, 6024]),
 array([  28, 1527, 3652, 6024]),
 array([  28, 1527, 3652, 6024]),
 array([  29, 1088, 3588, 5992]),
 array([  28, 1454, 3588, 5992]),
 array([  28, 1380, 3524, 5992]),
 array([  26, 1249, 3588, 5992]),
 array([  28,  947, 3524, 5992]),
 array([  25,  943, 3588, 5992]),
 array([  29, 1232, 3652, 5992]),
 array([  26, 1018, 3588, 5992]),
 array([  28, 1083, 3588, 5992]),
 array([  28, 1083, 3588, 5992]),
 array([  28, 1475, 3588, 5960]),
 array([  29, 1065, 3524, 5960]),
 array([  25, 1235, 3524, 5960]),
 array([  26,  935, 3460, 5960]),
 array([  28, 1179, 3524, 5960]),
 array([  27,  936, 3460, 5960]),
 array([  27, 1159, 3524, 5960]),
 array([  28, 1034, 3524, 5960]),
 array([  25, 1004, 3588, 5960]),
 array([  25, 